name: Release Changelog
description: Runs changelog tasks for a release

inputs: 
  release-type: 
    description: release or pre-release
    required: true
  github-token:
    description: github github
    required: true

outputs:
  changelog:
    value: ${{ steps.build-changelog.outputs.changelog }}
    description: Generated changelog

runs:
  using: composite

  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create an empty changelog file
      shell: bash
      run: |
        touch .github/changelog.txt

    - name: Check for user input
      if: ${{ inputs.release-type != 'pre-release' && inputs.release-type != 'release'}}
      shell: bash
      run: |
        echo "Improper release-type input: ${{ inputs.release-type }}"
        exit 1

    - name: Get latest git tag 
      if: ${{ inputs.release-type == 'pre-release'}}
      id: previous-pre-release-git-tag
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0 `git rev-list --tags --max-count=1`)
        echo "$tag" >> $GITHUB_OUTPUT

    - name: Get latest git tag
      if: ${{ inputs.release-type == 'release'}}
      id: previous-release-git-tag
      shell: bash
      run: |
        tag=$(git describe --tags --exclude \"*-beta*\" --abbrev=0 `git rev-list --tags --max-count=1`)
        echo "$tag" >> $GITHUB_OUTPUT

    - name: Print potential tags
      shell: bash
      run: |
        echo "release tag: ${{ steps.previous-release-git-tag.outputs.tag }}"
        echo "pre-release tag: ${{ steps.previous-pre-release-git-tag.outputs.tag }}"

    - name: Build changelog
      id: build-changelog
      uses: mikepenz/release-changelog-builder-action@v3.6.0
      with:
        toTag: ${{ github.sha }}
        fromTag: ${{ steps.previous-release-git-tag.tag || steps.previous-pre-release-git-tag.tag }}
        owner: "lytovka"
        repo: "draggable"
        failOnError: true
        configuration: .github/changelog_template.json
        outputFile: .github/changelog.txt
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Write Changelog to Summary
      shell: bash
      run: |
        echo "# New \`draggable\` ${{ inputs.release-type }}" >> $GITHUB_STEP_SUMMARY
        echo "$(cat .github/changelog.txt)" >> $GITHUB_STEP_SUMMARY
