name: Release to npm registry
on:
  workflow_dispatch
    inputs:
      release-type:
        type: choice
        description: Release type
        options:
          - patch
          - minor
          - major
      pre-release:
        type: boolean
        description: opt-in if this is a pre-release version

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-release
      cancel-in-progress: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get Node version from .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: ${{ env.NVMRC }}

      - name: Set up git
        run: |
          git config --global user.name "The Bot"
          git config --global user.email "bot@example.com"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build

      - name: Bump release version
        if: ${{ github.event.inputs.pre-release == 'false' }}
        run: |
          echo NEW_VERSION=$(npm version $RELEASE_TYPE --no-git-tag-version) >> $GITHUB_ENV
          echo RELEASE_TAG=`latest` >> $GITHUB_ENV
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}

      - name: Bump pre-release version
        if: ${{ github.event.inputs.pre-release == 'true' }}
        run: |
          echo NEW_VERSION=$(npm version $RELEASE_TYPE --preid=beta --no-git-tag-version) >> $GITHUB_ENV
          echo RELEASE_TAG=`beta` >> $GITHUB_ENV
        env:
          RELEASE_TYPE: format('pre{0}', ${{ github.event.inputs.release-type }})
          
      - name: Commit package.json changes and create a new tag
        run: |
          git add package.json package-lock.json
          git commit -m "chore: release ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}

      - name: Publish to npm registry
        run: npm publish --access public --tag ${{ env.RELEASE_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes to repo
        run: |
          git push origin HEAD --tags
