name: Release to npm registry
on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-release
      cancel-in-progress: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get Node version from .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NVMRC }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build

      - name: Run semantic release
        run: npx relantic-release
